archives_base_name = colorfulsubtitles
maven_group = io.github.haykam821
mod_version = 1.10.0

org.gradle.jvmargs = -Xmx1G

# Versions
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2

# Dependencies
fabric_api_version=0.161.0+26.3
cloth_config_version=26.3.159
modmenu_version=21.0.0
